version: "3"
services:
  openai-api:
    build: .
    container_name: openai-api
    working_dir: /work
    tty: true
    volumes:
      - type: bind
        source: ./work
        target: /work
    environment:
      - API_KEY
